pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh 'npm ci'
                    sh 'npm test'
                    sh 'mkdir -p reports'
                    sh 'rm -rf reports/coverage && mv coverage reports/'
                }
            }
            post{
                always{
                    junit 'bugtracker-frontend/test-results.xml'
                    publishHTML target: [
                        reportDir: 'bugtracker-frontend/reports/coverage',
                        reportFiles: 'index.html',
                        reportName: 'Frontend Code Coverage'
                    ]
                }
            }
        }

        stage('Launch test application'){
            agent{
                docker{
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps{
                sh 'docker compose up --build -d'
            }
        }

        stage('API Tests'){
            agent{
                docker{
                    image 'mcr.microsoft.com/playwright:v1.50.1-jammy'
                    reuseNode true
                    args '-u root --network="host"'
                }
            }
            steps{
                dir('tests-api'){
                    sh 'npx wait-port http://localhost:8080/api/health -t 30000'
                    sh 'npm ci'
                    sh 'npx playwright test'
                }
            }
            post{
                always{
                    junit 'tests-api/test-results/results.xml'
                    publishHTML target: [
                        reportDir: 'tests-api/playwright-report',
                        reportFiles: 'index.html',
                        reportName: 'API Test Report'
                    ]
                }
            }
        }

        stage('E2E Tests'){
            agent{
                docker{
                    image 'mcr.microsoft.com/playwright:v1.50.1-jammy'
                    reuseNode true
                    args '-u root --network="host"'
                }
            }
            steps{
                dir('tests-e2e'){
                    sh 'npx wait-port http://localhost:8080/api/health -t 30000'
                    sh 'npm ci'
                    sh 'npx playwright test'
                }
            }
            post{
                always{
                    junit 'tests-e2e/test-results/results.xml'
                    publishHTML target: [
                        reportDir: 'tests-e2e/playwright-report',
                        reportFiles: 'index.html',
                        reportName: 'E2E Test Report'
                    ]
                }
            }
        }
        
    }
    post {
        always {
            cleanWs()
        }
    }
}
