pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh 'npm ci'
                    sh 'npm test'
                    sh 'mkdir -p reports'
                    sh 'mv coverage reports/'
                }
            }
            post{
                always{
                    junit 'bugtracker-frontend/test-results.xml'
                    publishHTML target: [
                        reportDir: 'bugtracker-frontend/reports/coverage',
                        reportFiles: 'index.html',
                        reportName: 'Frontend Code Coverage'
                    ]
                }
            }
        }

        stage('Launch test application'){
            agent{
                docker{
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps{
                sh 'docker compose up --build -d'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
